version: "3"
services:
  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # 文字コードをutf8mb4にする（コンテナ上だとデフォルトでlatin1になる）
    environment:
      MYSQL_ROOT_PASSWORD: sysadm # rootユーザのパスワード
      MYSQL_DATABASE: tweet_app # データベース名
    volumes:
      - mysql-data:/var/lib/mysql # データを永続化するために必要
    ports:
      - "4306:3306"


  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/tweet_app
      - bundle:/usr/local/bundle # bundle installを毎回しなくて良くなる
    ports:
      - "3000:3000"
    links:
      - db

      
volumes:
  mysql-data:
  bundle: